### ISSUE TITLE
SP5 battery update would not install, failed parsing?

### ISSUE THREAD

**Issue by woberts** [StollD/linux-surface-firmware#2]
Thanks for your efforts to get firmware updates working for Surface.

I followed the instructions to enable this for my SP5 and got the following results. I can see that the cab file exists, but it appears to error out. Not sure what to try next?

$ fwupdmgr get-updates
No upgrades for Surface Pro System Firmware, current is 58.170.19200: 58.170.19200=same
UEFI Device Firmware has firmware updates:
Device ID:               7484f06a81214f6b662e178cf3e729e835929cc2
GUID:                    3624cd98-bdb6-461b-84a3-4f4853efc7e3
ID:                      io.tmsp.linux-surface-firmware.SurfacePro_5_6.SAM
Update Version:          239.12.7563
Update Name:             Surface Pro Update
Update Summary:          SAM firmware for Surface Pro 5 and Surface Pro 6, version 239.3101.139.0
Update Remote ID:        linux-surface
Update Checksum:         SHA1(7951582464a8709f379079325f219b917ff5da78)
Update Location:         firmware/b9250749f1e90d34d54ad0948a34809a06a3213ba292c825e7475ab521b755fd-SurfacePro_5+6_SAM_239.3101.139.0.cab
Update Description:      239.3101.139.0 improves battery performance.
                         
                         The computer will be restarted automatically after updating completely. Do NOT turn off your computer or remove the AC adaptor while update is in progress.
                         
No upgrades for UEFI Device Firmware, current is 56.2.60172: 56.2.60172=same
No upgrades for UEFI Device Firmware, current is 184.50.3448: 184.50.3448=same
No upgrades for UEFI Device Firmware, current is 173.0.266: 173.0.266=same
(base) [gb001609@sp5f ~]$ fwupdmgr -v update
No upgrades for Surface Pro System Firmware, current is 58.170.19200: 58.170.19200=same
Failed to parse URI 'firmware/b9250749f1e90d34d54ad0948a34809a06a3213ba292c825e7475ab521b755fd-SurfacePro_5+6_SAM_239.3101.139.0.cab'

**Comment by StollD** [comment]
I updated and regenerated the remote metadata (LVFS prefixes every file path with the full URL, which I didn't do). Can you try it again? You might need to force an update by running "fwupdmgr refresh".

**Comment by woberts** [comment]
Worked perfectly this time, thanks..
