### ISSUE TITLE
Possible to add Surface laptop 3

### ISSUE THREAD

**Issue by pinophyta** [StollD/linux-surface-firmware#5]
Will it be possible to add SL3 firmware into this repo as well? Thank you.

**Comment by droric** [comment]
How does one extract the firmware from the installer?  I wanted to grab the updated bin files for my System but was unsure how to do so.  I have SurfaceLaptop3_Win10_18362_20.010.3582.0.msi extracted into a folder but I don't see many bin files.

**Comment by pinophyta** [comment]
Thank you very much @archseer for adding Nov firmware.
